<?php
/**
 * @file
 *   Install hooks for ASCM CRM.
 */

/**
 * Implements hook_update_N().
 *
 * Delete field_deceased and field_date_of_death so they can be added again.
 */
function ascm_crm_update_7001() {
  if (field_info_field('field_deceased')) {
    field_delete_field('field_deceased');
  }
  if (field_info_field('field_date_of_death')) {
    field_delete_field('field_date_of_death');
  }
}
